### ISSUE TITLE
Something unexpected happened when do python -m pip install py-gen-mur  for mac

### ISSUE THREAD

**Issue by TimorCan** [lyy289065406/py-gen-mur#3]
NFO: pip is looking at multiple versions of pypiwin32 to determine which version is compatible with other requirements. This could take a while.
  Using cached pypiwin32-219.zip (4.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/57/3c_qvryd2rx6v7mcjdq0w1rh0000gn/T/pip-install-jytjuqir/pypiwin32_5b91ec8b86264c4aa048aac4cf70c758/setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by lyy289065406** [comment]
pypiwin32 is a third-party library for windows. It must not be installed on mac. Don’t mind this error. The way mac generates machine code will not use this lib
